// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkbmIkdmJB4pVkQfQaf_6nNRyfSW92pg0',
    appId: '1:1054759724577:web:763bc9e44ea48fce7ee560',
    messagingSenderId: '1054759724577',
    projectId: 'evently-1479d',
    authDomain: 'evently-1479d.firebaseapp.com',
    storageBucket: 'evently-1479d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1wIDyEWna4XCa4WuYr9vSIxLjsNpZ3C8',
    appId: '1:1054759724577:android:2654a8d003f628907ee560',
    messagingSenderId: '1054759724577',
    projectId: 'evently-1479d',
    storageBucket: 'evently-1479d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5oX5oPZ2X67ffgTZthTUfBkhmrEdmQL8',
    appId: '1:1054759724577:ios:b815eb45afd7069f7ee560',
    messagingSenderId: '1054759724577',
    projectId: 'evently-1479d',
    storageBucket: 'evently-1479d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5oX5oPZ2X67ffgTZthTUfBkhmrEdmQL8',
    appId: '1:1054759724577:ios:b815eb45afd7069f7ee560',
    messagingSenderId: '1054759724577',
    projectId: 'evently-1479d',
    storageBucket: 'evently-1479d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkbmIkdmJB4pVkQfQaf_6nNRyfSW92pg0',
    appId: '1:1054759724577:web:ab2a044003b15c177ee560',
    messagingSenderId: '1054759724577',
    projectId: 'evently-1479d',
    authDomain: 'evently-1479d.firebaseapp.com',
    storageBucket: 'evently-1479d.firebasestorage.app',
  );
}
